services:
  - type: web
    name: scrm-backend
    env: python
    plan: free
    rootDir: backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13

  - type: web
    name: scrm-frontend
    env: node
    plan: free
    rootDir: frontend
    buildCommand: "npm install --include=dev --legacy-peer-deps && npm run build"
    startCommand: "npm run start"
    envVars:
      - key: NODE_VERSION
        value: 20.11.0
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        fromService:
          type: web
          name: scrm-backend
          envVarKey: RENDER_EXTERNAL_URL
